- azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      location: "{{ location }}"
      name: "{{ env_name }}{{ regionprefix }}"
      purge_rules: yes
      state: "{{ delete_env }}"
      rules:
          - name: DenySSH
            protocol: Tcp
            destination_port_range: 22
            access: Deny
            priority: 100
            direction: Inbound
            source_address_prefix: 'INTERNET'
          - name: 'AllowRDP'
            protocol: Tcp
            source_address_prefix:
              - '1.1.1.1/32'
              - '2.2.2.2/32'
              - '3.3.3.3'
            destination_port_range: 3389
            access: Allow
            priority: 101
            direction: Inbound
          - name: 'AllowMultiplePorts'
            protocol: Tcp
            source_address_prefix:
              - '1.1.1.1/32'
              - '2.2.2.2/32'
              - '3.3.3.3'
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 120
          - name: 'AllowOctopus' 
            protocol: Tcp
            source_address_prefix:     
              - '1.1.1.1/32'
              - '2.2.2.2'
              - '{{OctoIP}}' 
            destination_port_range: '{{OctoPort}}' 
            access: Allow
            priority: 103
            direction: Inbound
          - name: 'AllowMultiplePortsOP'
            protocol: "*"
            source_address_prefix:
              - '1.1.1.1/32'
              - '2.2.2.2' 
            destination_port_range:
              - 5985
              - '{{portSFTP}}'
            access: Allow
            priority: 140 
          - name: 'IVR'
            protocol: "*"
            source_address_prefix: 'INTERNET'            
            destination_port_range: 6443
            access: Allow
            priority: 130
            direction: Inbound
          - name: 'TrackerService'            
            protocol: "*"
            source_address_prefix: 'INTERNET'
            destination_port_range: 11020
            access: Allow
            priority: 131            
            direction: Inbound
          - name: 'ComProxy'
            protocol: "*"
            source_address_prefix: 'INTERNET'
            destination_port_range: 8080
            access: Allow
            priority: 132
            direction: Inbound
          - name: 'TrackerOutbound'
            protocol: "*"
            source_address_prefix: 'VIRTUALNETWORK'
            destination_port_range: 11020
            access: Allow
            priority: 140
            direction: Outbound
          - name: 'LetsEncryptOutbound'
            protocol: "*"
            source_address_prefix: 'INTERNET'
            destination_port_range: 
              - 80
              - 443
            access: Allow
            priority: 141
            direction: Outbound
          - name: 'ComproxyOutbound'
            protocol: Tcp
            source_address_prefix: 'INTERNET'
            destination_port_range: 8080
            access: Allow
            priority: 142
            direction: Outbound
  ignore_errors: true
