Enable-WSManCredSSP -Role Server -Force
Add-Content -Path 'C:\PRG\SQLServer2019-DEV-x64-ENU\ConfigurationFile.ini' -Value '[OPTIONS]
IACCEPTPYTHONLICENSETERMS="False"
ACTION="Install"
IACCEPTROPENLICENSETERMS="False"
SUPPRESSPRIVACYSTATEMENTNOTICE="False"
ENU="True"
QUIET="True"
UpdateEnabled="False"
USEMICROSOFTUPDATE="False"
SUPPRESSPAIDEDITIONNOTICE="False"
FEATURES=SQLENGINE,REPLICATION,SNAC_SDK
HELP="False"
INDICATEPROGRESS="False"
X86="False"
INSTANCENAME="MSSQLSERVER"
INSTALLSHAREDDIR="C:\Program Files\Microsoft SQL Server"
INSTALLSHAREDWOWDIR="C:\Program Files (x86)\Microsoft SQL Server"
INSTANCEID="CBO"
SQLTELSVCACCT="NT Service\SQLTELEMETRY"
SQLTELSVCSTARTUPTYPE="Automatic"
INSTANCEDIR="C:\Program Files\Microsoft SQL Server"
AGTSVCACCOUNT="NT Service\SQLSERVERAGENT"
AGTSVCSTARTUPTYPE="Automatic"
COMMFABRICPORT="0"
COMMFABRICNETWORKLEVEL="0"
COMMFABRICENCRYPTION="0"
MATRIXCMBRICKCOMMPORT="0"
SQLSVCSTARTUPTYPE="Automatic"
FILESTREAMLEVEL="0"
SQLMAXDOP="2"
ENABLERANU="False"
SQLCOLLATION="SQL_Latin1_General_CP1_CI_AS"
SQLSVCACCOUNT="NT Service\MSSQLSERVER"
SQLSVCINSTANTFILEINIT="True"
SQLSYSADMINACCOUNTS="{{vm_user_name}}"
SAPWD="{{password}}"
SECURITYMODE="SQL"
SQLTEMPDBFILECOUNT="2"
SQLTEMPDBFILESIZE="8"
SQLTEMPDBFILEGROWTH="64"
SQLTEMPDBLOGFILESIZE="8"
SQLTEMPDBLOGFILEGROWTH="64"
TCPENABLED="0"
NPENABLED="0"
BROWSERSVCSTARTUPTYPE="Automatic"
SQLMAXMEMORY="2147483647"
SQLMINMEMORY="0"' -Force

Start-Sleep -s 30
Set-ExecutionPolicy -ExecutionPolicy Unrestricted
cmd.exe /C "C:\PRG\SQLServer2019-DEV-x64-ENU\setup.exe /IAcceptSQLServerLicenseTerms /ConfigurationFile=C:\PRG\SQLServer2019-DEV-x64-ENU\ConfigurationFile.ini /UpdateEnabled=False"

Set-Location 'C:\PRG\Oracle\'
Set-ExecutionPolicy -ExecutionPolicy Allsigned
cmd.exe /C "C:\PRG\ODAC\setup.exe -silent -nowelcome -noconfig -nowait"

